esphome:
  name: 32c3-i2s-mediaplayer
  friendly_name: 32c3-i2s-mediaplayer

esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino

external_components:
  - source: my_components

# Default value if not defined : GPIO1 GPIO18 GPIO0
media_player:
  - platform: singlecore_i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO1
    i2s_lrclk_pin: GPIO18
    i2s_bclk_pin: GPIO0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "keyhere"

ota:
  password: "passwordhere"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "32C3-I2S-Mediaplayer"
    password: "RrrNZQZobkw4"

captive_portal:
    